
set(CMAKE_VASM68K_SOURCE_FILE_EXTENSIONS s)
set(CMAKE_INCLUDE_FLAG_VASM68K "-I")


set(CMAKE_VASM68K_COMPILE_OBJECT
  "<CMAKE_VASM68K_COMPILER> <INCLUDES> <FLAGS> -L <OBJECT>.lst -o <OBJECT> <SOURCE>")

set(CMAKE_VASM68K_LINK_EXECUTABLE
  "${VLINK} <CMAKE_VASM68K_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")


set(CMAKE_VASM68K_OUTPUT_EXTENSION .o)
